version: "3.8"

services:

  db:
    build:
      context: ./sql
      dockerfile: /Dockerfile
    container_name: db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
    volumes:
      - db_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - thomasgreg_network

  api:
    build:
      context: .
      dockerfile: /Poc.ThomasGreg.API/Dockerfile
    container_name: api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=ThomasGregDb;User=sa;Password=P@ssw0rd
    depends_on:
      - db 
    networks:
      - thomasgreg_network

  mvc:
    build:
      context: .
      dockerfile: /Poc.ThomasGreg/Dockerfile
    container_name: mvc
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_BASE_URL=http://api:5001
    networks:
      - thomasgreg_network

networks:
  thomasgreg_network:
    driver: bridge

volumes:
  db_data:
